### ISSUE TITLE
cgraph.dll and gvc.dll missing on Windows

### ISSUE THREAD

**Issue by johnwason** [conda-forge/gazebo-feedstock#159] opened 2022-12-21 01:03 UTC
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I am getting errors for cgraph.dll and gvc.dll missing on Windows

### Installed packages

```shell
# Name                    Version                   Build  Channel
aom                       3.5.0                h63175ca_0    conda-forge
assimp                    5.2.5                h4dcb625_0    conda-forge
blosc                     1.21.3               hdccc3a2_0    conda-forge
boost-cpp                 1.78.0               h9f4b32c_1    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2022.12.7            h5b45459_0    conda-forge
cairo                     1.16.0            hd694305_1014    conda-forge
cfitsio                   4.2.0                h9ebe7e4_0    conda-forge
console_bridge            1.0.2                h5362a0b_1    conda-forge
cppzmq                    4.9.0                h449d27f_0    conda-forge
curl                      7.86.0               h68f0423_2    conda-forge
dirent                    1.21                          0    conda-forge
dlfcn-win32               1.3.0                h0e60522_0    conda-forge
eigen                     3.4.0                h2d74725_0    conda-forge
expat                     2.5.0                h1537add_0    conda-forge
ffmpeg                    5.1.2           gpl_h5b1d025_105    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.1               hbde0cde_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freeimage                 3.18.0              h064cf08_10    conda-forge
freetype                  2.12.1               h546665d_1    conda-forge
freexl                    1.0.6                h67ca5e6_1    conda-forge
gazebo                    11.12.0              ha5ac59a_4    conda-forge
geos                      3.11.1               h1537add_0    conda-forge
geotiff                   1.7.1                h4ffd875_4    conda-forge
gettext                   0.21.1               h5728263_0    conda-forge
glib                      2.74.1               h12be248_1    conda-forge
glib-tools                2.74.1               h12be248_1    conda-forge
gst-plugins-base          1.21.2               h001b923_0    conda-forge
gstreamer                 1.21.2               h6b5321d_0    conda-forge
gts                       0.7.6                h7c369d9_2    conda-forge
hdf4                      4.2.15               h1b1b6ef_5    conda-forge
hdf5                      1.12.2          nompi_h2a0e4a3_100    conda-forge
icu                       70.1                 h0e60522_0    conda-forge
imath                     3.1.6                h12be248_1    conda-forge
intel-openmp              2023.0.0         h57928b3_25922    conda-forge
jpeg                      9e                   h8ffe710_2    conda-forge
jsoncpp                   1.9.5                h2d74725_1    conda-forge
jxrlib                    1.1                  h8ffe710_2    conda-forge
kealib                    1.5.0                h61be68b_0    conda-forge
krb5                      1.20.1               h6609f42_0    conda-forge
lcms2                     2.14                 h90d422f_0    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libblas                   3.9.0              16_win64_mkl    conda-forge
libcblas                  3.9.0              16_win64_mkl    conda-forge
libccd-double             2.1                  h0e60522_3    conda-forge
libclang                  15.0.6          default_h77d9078_0    conda-forge
libclang13                15.0.6          default_h77d9078_0    conda-forge
libcurl                   7.86.0               h68f0423_2    conda-forge
libdeflate                1.14                 hcfcfb64_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libflang                  5.0.0           h6538335_20180525    conda-forge
libgdal                   3.6.1                h1cb26dd_1    conda-forge
libglib                   2.74.1               he8f3873_1    conda-forge
libhwloc                  2.8.0                h039e092_1    conda-forge
libiconv                  1.17                 h8ffe710_0    conda-forge
libignition-cmake2        2.16.0               h63175ca_1    conda-forge
libignition-common3       3.15.1               hc27e538_1    conda-forge
libignition-fuel-tools4   4.6.0                h4cc2e26_0    conda-forge
libignition-math6         6.13.0          py311h4b297e5_1    conda-forge
libignition-msgs5         5.9.0                hc6328b4_1    conda-forge
libignition-tools1        1.5.0                h63175ca_1    conda-forge
libignition-transport8    8.3.0                h252ff3b_1    conda-forge
libkml                    1.3.0             hf2ab4e4_1015    conda-forge
libnetcdf                 4.8.1           nompi_h8c042bf_106    conda-forge
libode                    0.16.2              h12c1d0e_11    conda-forge
libogg                    1.3.4                h8ffe710_1    conda-forge
libopenblas               0.3.21          pthreads_hc140b1d_3    conda-forge
libpng                    1.6.39               h19919ed_0    conda-forge
libpq                     15.1                 he840576_2    conda-forge
libprotobuf               3.21.12              h12be248_0    conda-forge
libraw                    0.20.2               h3eb7d9d_2    conda-forge
librttopo                 1.1.0               he22b5cd_12    conda-forge
libsdformat               9.8.0                h5ba8b87_4    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libspatialite             5.0.1               h07bf483_22    conda-forge
libsqlite                 3.40.0               hcfcfb64_0    conda-forge
libssh2                   1.10.0               h680486a_3    conda-forge
libtiff                   4.4.0                hc4f729c_5    conda-forge
libusb                    1.0.26             h8ffe710_100    conda-forge
libvorbis                 1.3.7                h0e60522_0    conda-forge
libwebp-base              1.2.4                h8ffe710_0    conda-forge
libxml2                   2.10.3               hc3477c8_0    conda-forge
libzip                    1.9.2                hfed4ece_1    conda-forge
libzlib                   1.2.13               hcfcfb64_4    conda-forge
llvm-meta                 5.0.0                         0    conda-forge
lz4-c                     1.9.3                h8ffe710_1    conda-forge
mkl                       2022.1.0           h6a75c08_874    conda-forge
ogre                      1.10.12             h7604e60_10    conda-forge
openal-soft               1.22.2               h2d74725_0    conda-forge
openblas                  0.3.21          pthreads_h1956dd5_3    conda-forge
openexr                   3.1.5                hab3b255_1    conda-forge
openh264                  2.3.1                h63175ca_1    conda-forge
openjpeg                  2.5.0                hc9384bd_1    conda-forge
openmp                    5.0.0                    vc14_1    conda-forge
openssl                   1.1.1s               hcfcfb64_1    conda-forge
pcre2                     10.40                h17e33f8_0    conda-forge
pip                       22.3.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h8ffe710_0    conda-forge
poppler                   22.12.0              ha6c1112_0    conda-forge
poppler-data              0.4.11               hd8ed1ab_0    conda-forge
postgresql                15.1                 h09b8c1b_2    conda-forge
proj                      9.1.0                h3863b3b_0    conda-forge
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
pugixml                   1.11.4               h0e60522_0    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
python                    3.11.0          h9a09f29_0_cpython    conda-forge
python_abi                3.11                    3_cp311    conda-forge
qt-main                   5.15.6               h068e40c_5    conda-forge
qwt                       6.2.0                h2db317d_4    conda-forge
ruby                      2.7.2                h1d9c0f5_8    conda-forge
sdl2                      2.26.1               h63175ca_1    conda-forge
setuptools                65.6.3             pyhd8ed1ab_0    conda-forge
simbody                   3.7                  hade3207_3    conda-forge
snappy                    1.1.9                hfb803bf_2    conda-forge
sqlite                    3.40.0               hcfcfb64_0    conda-forge
svt-av1                   1.4.1                h63175ca_0    conda-forge
tbb                       2021.7.0             h91493d7_1    conda-forge
tbb-devel                 2021.7.0             h91493d7_1    conda-forge
tiledb                    2.13.0               h5689973_0    conda-forge
tiny-process-library      2.0.4                h63175ca_1    conda-forge
tinyxml                   2.6.2                h2d74725_2    conda-forge
tinyxml2                  9.0.0                h0e60522_2    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
tzdata                    2022g                h191b570_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
urdfdom                   3.1.0                h33150cf_1    conda-forge
urdfdom_headers           1.1.0                h5362a0b_0    conda-forge
vc                        14.3                 h3d8a991_9    conda-forge
vs2015_runtime            14.32.31332          h1d6e394_9    conda-forge
wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
x264                      1!164.3095           h8ffe710_2    conda-forge
x265                      3.5                  h2d74725_3    conda-forge
xerces-c                  3.2.4                h63175ca_1    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
zeromq                    4.3.4                h0e60522_1    conda-forge
zlib                      1.2.13               hcfcfb64_4    conda-forge
zstd                      1.5.2                h7755175_4    conda-forge
zziplib                   0.13.69              h1d00b33_1    conda-forge
```

### Environment info

```shell
active environment : gazebo3
    active env location : C:\Users\u\.conda\envs\gazebo3
            shell level : 2
       user config file : C:\Users\u\.condarc
 populated config files : C:\Users\u\.condarc
          conda version : 22.9.0
    conda-build version : 3.21.9
         python version : 3.9.10.final.0
       virtual packages : __cuda=11.7=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\tools\miniconda3  (read only)
      conda av data dir : C:\tools\miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\tools\miniconda3\pkgs
                          C:\Users\u\.conda\pkgs
                          C:\Users\u\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\u\.conda\envs
                          C:\tools\miniconda3\envs
                          C:\Users\u\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/22.9.0 requests/2.26.0 CPython/3.9.10 Windows/10 Windows/10.0.19044
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by Tobias-Fischer** [comment] 2022-12-21 02:29
Looks like graphviz is missing run exports :(

**Comment by Tobias-Fischer** [comment] 2022-12-21 02:30
Can you try whether the error goes away if you manually install graphviz?

**Comment by johnwason** [comment] 2022-12-21 02:32
Yep, it launched with graphviz

**Comment by Tobias-Fischer** [comment] 2022-12-21 04:38
Ok - are you happy to open an issue in the graphviz feedstock?

**Comment by traversaro** [comment] 2022-12-21 11:54
This is indeed a regression on our side, see https://github.com/conda-forge/gazebo-feedstock/pull/154 .

**Comment by traversaro** [comment] 2022-12-21 12:02
I opened https://github.com/conda-forge/graphviz-feedstock/pull/111 . If it is merged quickly, I will then trigger a re-build of gazebo to take into account this new constraint, otherwise if it takes some time I will manually added the constraint a re-build the package.

**Closed** 2022-12-23 15:37 UTC
Labels: bug
